### ISSUE TITLE
How to execute your codes? Where can I get your paper? Thanks!

### ISSUE THREAD

**Issue by Chijingqian** [fei-hdu/NAS-Lung#1]
Hi, fei.
Thanks for sharing your great work!  I have some questions to ask you.

How to execute your codes? What is the order of executing your codes?
Where can I get your paper? If I use your code which paper should be referenced?

Thank you very much!
Best regards,
Chi Jingqian.

**Comment by dailybudushu** [comment]
Please refer to README.md for how to run the code and References.
The paper has been submitted, and the address will be published on Github after the official publication.

**Comment by Chijingqian** [comment]
Thanks very much for your answer!
Best regards

**Comment by fei-aiart** [comment]
The pre-proof version of our paper is now availabel at https://www.sciencedirect.com/science/article/pii/S0031320321000121.
